<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="omnibot">

  <xacro:property name="base_length" value="0.200"/>
  <xacro:property name="base_width" value="0.140"/>
  <xacro:property name="base_height" value="0.0764"/>

  <xacro:property name="wheel_width" value="0.036"/>
  <xacro:property name="wheel_radius" value="0.039"/>

  <xacro:property name="wheel_x_offset" value="0.06"/>
  <xacro:property name="wheel_y_offset" value="${base_width/2 + wheel_width/2 + 0.0165}"/>
  <xacro:property name="wheel_z_offset" value="${-base_height/2 + 0.0228}"/>

  <xacro:property name="M_PI" value="3.14159"/>

  <xacro:include filename="$(find omnibot_description)/urdf/base.urdf.xacro"/>
  <xacro:include filename="$(find omnibot_description)/urdf/wheel.urdf.xacro"/>
  <xacro:include filename="$(find omnibot_description)/urdf/sensors.urdf.xacro"/>

  <xacro:omnibot_base/>

  <xacro:omnibot_wheel prefix="front_right">
    <origin xyz="${wheel_x_offset} ${-wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
  </xacro:omnibot_wheel>
  <xacro:omnibot_wheel prefix="front_left">
    <origin xyz="${wheel_x_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
  </xacro:omnibot_wheel>
  <xacro:omnibot_wheel prefix="back_left">
    <origin xyz="${-wheel_x_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
  </xacro:omnibot_wheel>
  <xacro:omnibot_wheel prefix="back_right">
    <origin xyz="${-wheel_x_offset} ${-wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
  </xacro:omnibot_wheel>

  <xacro:imu>
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
  </xacro:imu>

  <xacro:lidar>
    <origin xyz="-0.013 0.0 ${base_height/2 + 0.024}" rpy="0.0 0.0 0.0"/>
  </xacro:lidar>

  <xacro:camera>
    <origin xyz="${base_length/2 - 0.0014} 0.0 0.018" rpy="0.0 0.0 0.0"/>
  </xacro:camera>

  <gazebo>
      <plugin filename="libignition-gazebo-joint-state-publisher-system.so"
            name="ignition::gazebo::systems::JointStatePublisher"/>
  </gazebo>

</robot>
